services:
  vehicle-rental-management-system-mysql:
    container_name: vehicle-rental-management-system-mysql-dev
    ports:
      - '33063:3306'

  vehicle-rental-management-system-php:
    container_name: vehicle-rental-management-system-php-dev
    environment:
      APP_ENV: dev
      APP_VERSION: dev
      DATABASE_URL: mysql://root:@vehicle-rental-management-system-mysql:3306/vehicle-rental-management-system_dev

  vehicle-rental-management-system-nginx:
    container_name: vehicle-rental-management-system-nginx-dev
    ports:
      - '8083:80'

  vehicle-rental-management-system-prometheus:
    container_name: vehicle-rental-management-system-prometheus-dev
    ports:
      - '9090:9090'

  vehicle-rental-management-system-redis:
    container_name: vehicle-rental-management-system-redis-dev

  vehicle-rental-management-system-grafana:
    container_name: vehicle-rental-management-system-grafana-dev
    ports:
      - '3000:3000'

  vehicle-rental-management-system-mtail:
    container_name: vehicle-rental-management-system-mtail-dev
    ports:
      - '3903:3903'