version: '3.7'

services:
  vehicle-rental-management-system-mysql:
    container_name: vehicle-rental-management-system-mysql-dev
    ports:
      - '33063:3306'

  vehicle-rental-management-system-php:
    container_name: vehicle-rental-management-system-php-dev
    environment:
      APP_ENV: dev
      APP_VERSION: dev
      DATABASE_URL: mysql://root:@vehicle-rental-management-system-mysql:3306/vehicle-rental-management-system_dev

  vehicle-rental-management-system-nginx:
    container_name: vehicle-rental-management-system-nginx-dev
    ports:
      - '8083:80'
